CREATE TABLE IF NOT EXISTS watchlist_items (
  symbol TEXT NOT NULL UNIQUE,
  market TEXT NOT NULL,
  display_name TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
